parsing plugins remodularization
aml-org/amf-core pull request #178
Opened 2021-03-11 19:50 UTC by AgustinBettati

This PR includes:
- APIMF-2877: definition of parsing plugins and adoption in AMFCompiler
- APIMF-2905: remove validation methods from parse plugin interface
- APIMF-2907: create default environments with parsing plugins
- APIMF-2880: define interface for fallback mechanism when no plugin is matched

2021-03-12 20:48 UTC, tomsfernandez commented on shared/src/main/scala/amf/client/remod/AMFRender.scala
> +private[remod] object AMFRender {
Why have separate methods instead of writers or something like that? Same signature but writing is changed. Both writers would receive YNodes

2021-03-12 20:50 UTC, tomsfernandez requested changes
Would probably mark all classes that have to be worked upon with a TODO or something to really know which to review or not.

2021-03-15 21:27 UTC, looseale submitted a review, later dismissed

2021-03-16 15:48 UTC, tomsfernandez approved these changes

2021-03-16 15:52 UTC, nschejtman approved these changes

2021-03-16 15:58 UTC, merged